require("sultanov.plugins-setup")
require("sultanov.core.options")
require("sultanov.core.keymaps")
require("sultanov.core.colorscheme")
require("sultanov.plugins.comment")
require("sultanov.plugins.nvim-tree")
require("sultanov.plugins.lualine")
require("sultanov.plugins.nvim-cmp")
